sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t haoly142/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true haoly142/docker-react npm run test
